apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9okqt/10CnMlNUV6rn6IrBT4+aeCbTweBJMZjEQ+3VEa0nGXR5UfswbGSNCZPFG3mhUr5ow=,iv:wC6rJDsdl8QSQ7XO9wOS+YDhhXM/5YZo6lD4+lv6y4E=,tag:goYqhAC4wGi30IZwSK6n8g==,type:str]
sops:
  age:
    - recipient: age1lk954y2c3hfgfvl45fkn0wn5u7mvkr5pk0wqzcn0lfpwndqnk4uskas5pw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZzlhUTB2ckpGNXRUNVRG
        VjhtY1p5ZXB0Y1lnTzB3a29TaEJ5WVkrd1RrClVEemhFOWFWZGRKUWhJazdWUkhV
        dXMwdEJGL3N1RDhqSzhBYjVUdXRqdDQKLS0tIGZqSmppL1RHV2t3QWVLL1pHQ0Q1
        Vk9hcUZIcFFWV2R3WXdISFk4VkpKRUkK+4aVeoSFnENf2XVOyi3H4mBRqocPyT0m
        vVV9Et7oz5w5D8mF7Um+GfDb1W7aW8erk2pZ2eDqGq1LS37dbliajQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T10:37:22Z"
  mac: ENC[AES256_GCM,data:j/k/XmF6Pokadq7L0xtu2exGL+kB+gmT25G8PJDPSXfAOKDakgf/jxpDomWRA18UFJ/Q9otKta49l01NKiifMqxRlbzJ+UoL2ipZUlOqlS/XDnmCEUpF5bB9Wk+6fR6wdy36AMQl5SqJNpDuFbtfthtyiVSfIIiXlHEnFxXo4kM=,iv:Ko6CvWDS8J9irvwqwxgktnAXHy13ntiwKW6Y/rfVrbg=,tag:TjgPi7a/fTkl7m/4GtopOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
