apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mBucfzTrLi5ry+sx,iv:XTXoPG8agDV4FsJ6YHa3JyPkaWgSHPmlC/L038qgOdY=,tag:bpCSXdZ2K1VnG4VsNeD6Gw==,type:str]
sops:
  age:
    - recipient: age1lk954y2c3hfgfvl45fkn0wn5u7mvkr5pk0wqzcn0lfpwndqnk4uskas5pw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMzI2cHBHS3BiWVh2ajhl
        aVZnakxnaHJYck54ald4Z2NidXNqU2toY0NnCk50dHd6bTkxdHE5TGRzeHY0Skly
        VXZPOUdhcnR4dW5UcHVRRkxQSXF1RUUKLS0tIG1OZEZSTG51WnE0NkRCYW55NElt
        NTBYYnB2Z0dLOTV6TVVmVEpUNFk0bTgKayMkhZk+dBX4iHwl2iC1/ZAM9JxJ9bCN
        paXHjQq2d+eZI7VYwKzOTrhU65v/GEy+ZymITMCwjQiKgXlN+jOUFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T10:37:22Z"
  mac: ENC[AES256_GCM,data:djCrx4XRAjckdDZSiY/+YEJTrQyxp2UaUt++fw0wM/wagr0dJzbI9mpfAvRUz6NRu/6m7v/omkWoh34+qdCnmfPACRWHgbgIkNGQZfcXyInz4Rpp+ByIsQFnZpmqQXX64QyPVGDLqqrbCnpEVDnqqNJKQJ1VR1DdHt64w/OkH18=,iv:nIYvGTMPPAPVwy80+0FarifJwnMcJoHw0DLD4QCsSXM=,tag:vjFALmgxNWV21EnrZ0eayA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
