apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:gNqmFnICb3pLWa4C5JpDGXI3LiOfpVZ69BTH5UcDeqM=,iv:mLrVCCy2G0V+R5ceZP2KUT++Hr2aOyC9eF7wrnF2+zg=,tag:SaQKEUJD0HDmlrGELLTebA==,type:str]
sops:
  age:
    - recipient: age1lk954y2c3hfgfvl45fkn0wn5u7mvkr5pk0wqzcn0lfpwndqnk4uskas5pw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydHhadW9iN1luSlZTQmtF
        dlFMaWRlbExTN29GNFdjenBGbmZ5cXZZQWdzCjFzSGd6UVRaWTZ4Sm5yWDdZMlhQ
        dWsvbnF2QTBqN0JiKytnTGxDM0ZGaVEKLS0tIHhGVkxsalh1TVJ6RXdtQ3R0emhz
        NzB0dzdadzdJMHlESS9KdmdSN2laNnMKd/4JZ7FHizdiuZwogwTU0oIWIHnyeD1t
        x/kVVHEZdOJGUpm1//dFzVJUff4B3afGrIxsES+pvthfQRCMTYGjRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T10:37:22Z"
  mac: ENC[AES256_GCM,data:sxGRThO+6NXpu3YPDY6gmASy/mc6ireH9qjD32vNT6xZ3VAMy7QNgTCK1MfOYKL62kdf2VcDw6MwVuaR+/hDNlNwh8moiePjxqTmtUvthgjnOHoCqn8HKFyHdym0lI8XGwB9PH4ErCMvx6ilcuEIJUZW0ouTjjTjxxYkWuVA1t4=,iv:y6eQD82ENpalhB3z+v42bdj4WjgHfgqM/Fdhc1aRLXM=,tag:nbS//tu8rCC4K4L6h2ZwTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
