apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:mCHUsOZro4Y0Y4d6gnQx42eTY8PuVnG/hJzw9Jqumo7NnxnzAfrJoaKJht3nq//YLhVDJZEp/0LT9ujYS/wQZhWCCVUfwTkAs7sOAYiNp0+faARu44+kEDCPNaxzTYxa73/uyjgm9ZFDxmo/piWpfPCE4IDYV0QtHndjCG4BMF5Q0r6/UN+3oAr8Lal01W22apkKHhjp/cbsHtzccyzh2wHFCZmn0+2qXMK2fhGNXWe3k1L7,iv:T+6GX6TLfEBBjFC5syU0Df3yyu/NSP27ZUhz2FzyL/8=,tag:JYNJJOCrSpdVj8E7HL1ynw==,type:str]
sops:
  age:
    - recipient: age1lk954y2c3hfgfvl45fkn0wn5u7mvkr5pk0wqzcn0lfpwndqnk4uskas5pw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOVpKdGVsRlZlS1JZL0w3
        bG1naWNKQTVEaVdnR0Jyc2toaE9jZnZpVlVZCnpkUlF3ZzFUd2xZWXNDcVBwdDh4
        TlEvYXZ0VmJaN1RocHFNdXFidmhYZ0UKLS0tIERlZGQ3OUZ3OVhUKzFjMEs3bUI1
        OWJBZnhYczFxS0lkWk9rSFB5dEVzYmcKzPBakEbuM0qTSXNAjzPKGmfBrD6RiaqT
        4f1GwHyjt4Tx66SlygeGttYOEaXk2BQzezej/klJ4jpqihiVZDU3lA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T10:37:22Z"
  mac: ENC[AES256_GCM,data:JZlV8clhKTv+NxEKB8IG0fdP2fluLrsM23aDMBeA/druXOS5mino0XFXjXt5aK4K4QdM+kR8f8GduPd752QaseoSMR9efCmb8yuNU11HDjVaYRDioW97ZW3TYxlxtWUB3xmRedZCkBrZyunZ4c7DElIHW7Ar1DSU3DHXRIHmKA0=,iv:3iTw9dbq4NnT6zYzotTj2pI9gv3W+PVeQ0OGqK5Bdp4=,tag:EccEKQzI2Het/mWk4gusyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
