apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:UHkDHUJKGXuJFFqbtpG/9rW61h8L1muW2vmz2LnqUfkjHYS4JjoNxi+rio/3FSQ6RVpnFig=,iv:R7rdiWSZRaRe0BDluPWk++Fk9lv4BURYDQQwW6aKvLI=,tag:+5jPZMck4see0CC5wchLzg==,type:str]
sops:
  age:
    - recipient: age1lk954y2c3hfgfvl45fkn0wn5u7mvkr5pk0wqzcn0lfpwndqnk4uskas5pw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWhyd1RGaXpBVFNZWnlW
        VDMzQVNQVlZPMGxIWHoyaW9CQm1OVFpiYnlNCk4xYUN2eDNmZk9FOVBjSGhNeEI3
        dDhQOWNxM3hGSzR6ajgyOHpDOWJSZEkKLS0tIG9KL1ZkdFhFYlVGOHpjSmxpdjc3
        TnZnQXkxWkRHMXViemRzQWdWeGsxMHMKxYG6c5ScK8i+p01slInc8GHh2PGXAqyd
        C66ulfUHEp6Y4m34VFN6fWTE4VVUr2cqCLhTpVsACTFPkdwkThoqAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T10:37:22Z"
  mac: ENC[AES256_GCM,data:bkQDyeHFv+fDi9jf2mDHnm6VxHUyPQBnwDwfTyI0NGp+p6eAtUXJd9gP4n5kxP5Hlo1C3Z/ek/2+rIWEd5pfE06o49OrwiMPNIJggUpDtR2ArujyxFimB5IOqUwA/zDe08OeZDCfqepd+g7maOOs+olyeJU4QZjn/jO/hqODzb8=,iv:Ca0ditLhADIfeZ518DBv/UEfRm7oDkQ+7s5TpXnNmQI=,tag:nMc7hGd0XE4V6vrZBQJggg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
