---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.239:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.239"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-admin1"
    ipAddress: "192.168.0.80"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:00:ce:9e"
        dhcp: false
        addresses:
          - "192.168.0.80/24"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.0.239"
  - hostname: "talos-worker1"
    ipAddress: "192.168.0.81"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:f0:8a:f3"
        dhcp: false
        addresses:
          - "192.168.0.81/24"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.0.239"
  - hostname: "talos-worker2"
    ipAddress: "192.168.0.82"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:de:60:24"
        dhcp: false
        addresses:
          - "192.168.0.82/24"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.0.239"
  - hostname: "talos-worker3"
    ipAddress: "192.168.0.83"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:64:d3:de"
        dhcp: false
        addresses:
          - "192.168.0.83/24"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.0.239"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

